use Test::More;
use strict;

use Util::All '-data';

ok(defined &dualvar);
ok(defined &looks_like_number);
ok(defined &openhandle);
ok(defined &refaddr);
ok(defined &reftype);
ok(defined &set_prototype);
ok(defined &weaken);
ok(defined &has_utf8);
ok(defined &unbless);
ok(defined &is_scalar_ref);
ok(defined &is_array_ref);
ok(defined &is_hash_ref);
ok(defined &is_code_ref);
ok(defined &is_glob_ref);
ok(defined &is_rx);
ok(defined &is_instance);
ok(defined &is_invocant);
ok(defined &is_value);
ok(defined &is_string);
ok(defined &is_number);
ok(defined &is_integer);
ok(defined &is_readonly);
ok(defined &is_weak);
ok(defined &is_vstring);
ok(defined &is_tainted);
ok(defined &is_blessed);
done_testing;