package Util::All::Plugin::Csv;

use warnings;
use strict;

use Util::Any -Base, -Pluggable;

sub utils {
  {
  '-csv' => [
    [
      'Text::CSV',
      '',
      {
        'parse_csv' => sub {
            my($pkg, $class, $func, $args, $kind_args) = @_;
            $args ||= {};
            $kind_args ||= {};
            use strict 'refs';
            if (not defined &Util::All::_Tmp::Text::CSV_XS::next) {
                no strict 'refs';
                *{'Util::All::_Tmp::Text::CSV_XS::next';} = sub {
                    my $self = shift @_;
                    my $r;
                    not $$self{'pass_fh'} and close $$self{'fh'} unless $r = $$self{'sub'}();
                    return $r;
                }
                ;
            }
            sub {
                my $pass_fh = 0;
                my($fh, $column_names) = @_;
                my $csv = 'Text::CSV_XS'->new({'binary', 1, %$kind_args, %$args});
                if (not ref $fh) {
                    my $file = $fh;
                    undef $fh;
                    Carp::croak("cannot open file: $file") unless open $fh, '<', $file;
                }
                else {
                    $pass_fh = 1;
                }
                my $sub;
                if (@_ == 2) {
                    $csv->column_names($column_names);
                    $sub = sub {
                        $csv->getline_hr($fh);
                    }
                    ;
                }
                else {
                    $sub = sub {
                        $csv->getline($fh);
                    }
                    ;
                }
                return bless({'sub', $sub, 'fh', $fh, 'pass_fh', $pass_fh}, 'Util::All::_Tmp::Text::CSV_XS');
            }
            ;
        },
        '-select' => []
      }
    ]
  ]
}
;
}

=head1 NAME

Util::All -  (alpha software) collect perl utilities and group them by appropriate kind.

=cut

our $VERSION = '0.01';

=head1 SYNOPSIS

=head1 EXPORT

functions which C<*> follows are generated by the way like Sub::Exporter.
see L<Util::Any/"USE Sub::Exporter's GENERATOR WAY">

=head2 -csv

=head3 parse_csv *

  use Util::All -csv;
  
  my $csv = parse_csv($file_or_fh);
  while (my $ar = $csv->next) {
     print "@$ar\n";
  }
  
  my $csv = parse_csv($file_or_fh, ['name', 'age']);
  while (my $hr = $csv->next) {
     print jion " ", %$hr, "\n";
  }
  
  # pass options to Text::CSV_XS
  use Util::All -csv => {-args => {binary => 0, eol => "\r\n"}};


=head3 test code

 package test_csv1;
 use Util::All -csv;
 my $csv = parse_csv("t/data/test.csv");
 my $sum = 0;
 while (my $l = $csv->next) {$sum +=$l->[1]};
 $sum;
 # equal to: 223

 package test_csv2;
 use Util::All -csv;
 my $csv = parse_csv("t/data/test.csv", ['l', 'num']);
 my $label = '';
 while (my $l = $csv->next) {$label .=$l->{l}};
 $label;
 # equal to: "abcdefアイウエオ"

 package test_csv3;
 use Util::All -csv;
 open my $fh, "t/data/test.csv";
 my $csv = parse_csv($fh);
 my $sum = 0;
 while (my $l = $csv->next) {$sum +=$l->[1]};
 $sum;
 # equal to: 223

 package test_csv4;
 use Util::All -csv;
 open my $fh, "t/data/test.csv";
 my $csv = parse_csv($fh);
 1 while $csv->next;
 tell $fh;
 # equal to: 49



=head1 AUTHOR

Ktat, C<< <ktat at cpan.org> >>

=head1 REPOSITORY

Util::All is hosted at github.

L<http://github.com/ktat/Util-All>

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

 perldoc Util::All::Csv

You can also look for information at:

=over 4

=item * RT: CPAN's request tracker

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=Util-All>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/Util-All>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/Util-All>

=item * Search CPAN

L<http://search.cpan.org/dist/Util-All/>

=back

=head1 ACKNOWLEDGEMENTS

Thanks to All Perl Users.
When I find useful code, I write it here as memo.

=head1 SEE ALSO

=over 4

=item L<Util::Any>

This module is based on Util::Any.
Util::Any helps you to create your own utility module.

=back

=head1 COPYRIGHT & LICENSE

Copyright 2009-2010 Ktat, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut

1;