package Util::All::Plugin::Xml;

use warnings;
use strict;

use Util::Any -Base, -Pluggable;

sub utils {
  {
  '-xml' => [
    [
      'XML::Simple',
      '',
      {
        '-select' => [],
        'to_xml' => sub {
            my($pkg, $class, $func, $args, $kind_args) = @_;
            $$args{'KeyAttr'} ||= $$kind_args{'key_attr'} || $$args{'key_attr'};
            sub {
                XML::Simple::XMLout(shift @_, %$args);
            }
            ;
        },
        'from_xml' => sub {
            my($pkg, $class, $func, $args, $kind_args) = @_;
            local $XML::Simple::XML_SIMPLE_PREFERRED_PARSER = $$kind_args{'parser'} || $$args{'parser'} || 'XML::Parser';
            $$args{'Forcearray'} ||= $$kind_args{'force_array'} || $$args{'force_array'};
            $$args{'KeyAttr'} ||= $$kind_args{'key_attr'} || $$args{'key_attr'};
            sub {
                XML::Simple::XMLin(shift @_, %$args);
            }
            ;
        }
      }
    ]
  ]
}
;
}

=head1 NAME

Util::All::Plugin::Xml; -  Util::All plugin for Xml

=cut

=head1 EXPORT

functions which C<*> follows are generated by the way like Sub::Exporter.
see L<Util::Any/"USE Sub::Exporter's GENERATOR WAY">

=head2 -xml

=head3 to_xml *

  sub {
      my ( $pkg, $class, $func, $args, $kind_args ) = @_;
      $args->{KeyAttr} ||= $kind_args->{key_attr} || $args->{key_attr};
      sub {
          XML::Simple::XMLout( shift, %$args );
        }
    }


=head3 from_xml *

  sub {
      my ( $pkg, $class, $func, $args, $kind_args ) = @_;
      local $XML::Simple::XML_SIMPLE_PREFERRED_PARSER =
           $kind_args->{parser}
        || $args->{parser}
        || 'XML::Parser';
      $args->{Forcearray} ||= $kind_args->{force_array} || $args->{force_array};
      $args->{KeyAttr}    ||= $kind_args->{key_attr}    || $args->{key_attr};
      sub {
          XML::Simple::XMLin( shift, %$args );
        }
    }




=head1 AUTHOR

Ktat, C<< <ktat at cpan.org> >>

=head1 REPOSITORY

Util::All is hosted at github.

L<http://github.com/ktat/Util-All>

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

 perldoc Util::All::Xml

=head1 SEE ALSO

=over 4

=item L<Util::All>

collect perl utilities and group them by appropriate kind.

=item L<Util::Any>

This module is based on Util::Any.
Util::Any helps you to create your own utility module.

=back

=head1 COPYRIGHT & LICENSE

Copyright 2009-2010 Ktat, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut

1;